version: '3.8'

services:
  # バックエンドAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: image-processor-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - JWT_SECRET=your-local-jwt-secret-change-in-production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-northeast-1
      - S3_BUCKET_NAME=your-bucket-name
      - CORS_ORIGIN=https://your-vercel-app.vercel.app
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - /app/node_modules
    depends_on:
      - localstack
    networks:
      - app-network

  # ローカルS3モック（LocalStack）
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
    volumes:
      - ./localstack-data:/var/lib/localstack
    networks:
      - app-network

networks:
  app-network:
    driver: bridge