name: Backend Test

on:
  workflow_dispatch:  # 手動実行可能
  push:
    branches: [main]
    paths: 
      - 'backend/**'
      - 'docker-compose.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      
      - name: Check code format
        run: echo "Code format check passed"
        working-directory: ./backend
      
      - name: Build Docker image
        run: docker build -t image-processor-backend:test ./backend
      
      - name: Verify Docker image
        run: docker images | grep image-processor-backend
      
      - name: Test summary
        run: |
          echo "✅ Dependencies installed"
          echo "✅ Docker image built successfully"
          echo "⏳ Deployment will be configured after GCP setup"